import { Project } from "@/types";

export const PROJECTS: Project[] = [
  {
    id: "1",
    title: "Suffer",
    roles: ["Lighting Technician"],
    thumbnail: "/images/frames/OIP.jpg",
    description: "sdadsasdaadsaasdasdasasddassahjsgfgkjxzcbjkcbzjkcbjksfjkhdakdhasjkhzjxcbzmxbcsjkafasjkdhajkhdaskjdhasdkjxzcbakjdaskdh",
    year: "2026",
    category: "Short Film",
    url: "https://abcd",
  },
  {
    id: "2",
    title: "The Silent Echo",
    roles: ["Director, Editor"],
    thumbnail: "/images/frames/OIP-2.jpg",
    description: "dasdaddasd",
    year: "2026",
    category: "Short Film",
    url: "https://abcd",
  },
  {
    id: "3",
    title: "The Silent Echo",
    roles: ["Director, Editor"],
    thumbnail: "/images/frames/OIP-2.jpg",
    description: "dasdaddasd",
    year: "2026",
    category: "Short Film",
    url: "https://abcd",
  },
  {
    id: "4",
    title: "The Silent Echo",
    roles: ["Director, Editor"],
    thumbnail: "/images/frames/OIP-2.jpg",
    description: "dasdaddasd",
    year: "2026",
    category: "Short Film",
    url: "https://abcd",
  },
  {
    id: "5",
    title: "The Silent Echo",
    roles: ["Director, Editor"],
    thumbnail: "/images/frames/OIP-2.jpg",
    description: "dasdaddasd",
    year: "2026",
    category: "Short Film",
    url: "https://abcd",
  },
  {
    id: "6",
    title: "The Silent Echo",
    roles: ["Director, Editor"],
    thumbnail: "/images/frames/OIP-2.jpg",
    description: "dasdaddasd",
    year: "2026",
    category: "Short Film",
    url: "https://abcd",
  },
  {
    id: "7",
    title: "The Silent Echo",
    roles: ["Director, Editor"],
    thumbnail: "/images/frames/OIP-2.jpg",
    description: "dasdaddasd",
    year: "2026",
    category: "Short Film",
    url: "https://abcd",
  },
];